thetooth:
  build: .
  environment:
    VIRTUAL_HOST: "thetooth.name"
    VIRTUAL_PORT: "9000"
    BINDING: "0.0.0.0:9000"
  volumes:
   - /home/thetooth/public_html/images:/opt/server/images
   - /home/thetooth/public_html/tmp:/opt/server/tmp
  expose:
   - "9000"
