---

- hosts: all
  tasks:
    - name: Deploy thetooth.name to staging
      docker_container:
        name: thetooth-name-staging
        image: thetooth/thetooth.name:latest
        recreate: yes
        state: started
        pull: yes
        ports:
          - "0.0.0.0:9101:9000"
        volumes:
          - /home/thetooth/public_html/images:/opt/thetooth.name/images:ro
          - /home/thetooth/public_html/images/thumbs:/opt/thetooth.name/images/thumbs:rw
      when: prod is undefined

    - name: Deploy thetooth.name to production
      docker_container:
        name: thetooth-name
        image: thetooth/thetooth.name:prod
        recreate: yes
        state: started
        pull: yes
        exposed_ports:
          - 9000
        env:
          VIRTUAL_HOST: thetooth.name
          VIRTUAL_PORT: 9000
        volumes:
          - /home/thetooth/public_html/images:/opt/thetooth.name/images:ro
          - /home/thetooth/public_html/images/thumbs:/opt/thetooth.name/images/thumbs:rw
          - /home/thetooth/public_html/tmp:/opt/thetooth.name/tmp:ro
      when: prod is defined